### ISSUE TITLE
Plain text Auth Token

### ISSUE THREAD

**Issue by palicao** [vlrprbttst/partita-domani-a-roma#2]
Pubblicare l'auth token in chiaro su github può essere un problema di sicurezza. Qualcuno potrebbe usare lo stesso token per superare il rate-limit impedendo così al sito di aggiornare le info sulle prossime partite!
Vedi https://github.com/vlrprbttst/partita-domani-a-roma/blob/master/js/custom/services/matchesprovider.js#L32

**Comment by vlrprbttst** [comment]
grande! grazie mille, provvediamo a correggere
