### ISSUE TITLE
Wrong element positioning on small desktop devices

### ISSUE THREAD

**Issue by vtombesi** [vlrprbttst/partita-domani-a-roma#3]
On my Mac Book Pro, the "Domani/Oggi/ button is above the text. 

![schermata 2016-01-19 alle 09 38 48](https://cloud.githubusercontent.com/assets/583774/12413623/a184e96e-be90-11e5-8cc2-66c42d426b4c.png)

**Comment by vlrprbttst** [comment]
thanks a lot valentino, this will be fixed asap :sweat_smile:
